# Yoga Sutras File Prep

This notebook prepares a JSON file that lets us show verses from the Yoga Sutras. I found a [spreadsheet with the Yoga Sutras](https://docs.google.com/spreadsheets/d/1HrfWM7KeBPHHOCXbpKMVk3oTV9nrOZYr/edit?usp=drive_link&ouid=101257354704441160839&rtpof=true&sd=true) from a Sanskrit student on [this Reddit post](https://www.reddit.com/r/yoga/comments/17zf5co/yoga_sutras_in_excel_with_wordforword_translation/). This was a great starting point!

All I had to do to get started was read it in, rename some columns, and write it back out as JSON. Maybe I'll add to it later. It might be good to add more translations that I like.

NOTE: I did not run this in the project venv. I used a separate one that had `polars` and `fastxml` installed.

In [ ]:
import polars as pl

In [ ]:
#df = pl.read_excel("YogaSutraDecomposed.xlsx", sheet_name="Ch1")
#df.head()

In [7]:
data = []
for sheet in ["Ch1", "Ch2", "Ch3", "Ch4"]:
    df = pl.read_excel("YogaSutraDecomposed.xlsx", sheet_name=sheet)
    display(df.head())
    data.append(df)

shape: (5, 7)
┌──────────────────┬──────────────────┬──────────────────┬──────┬───────┬──────────────────┬───────┐
│ Brahmi           ┆ IAST             ┆ IPA              ┆ Book ┆ Sutra ┆ English          ┆ Gloss │
│ ---              ┆ ---              ┆ ---              ┆ ---  ┆ ---   ┆ ---              ┆ ---   │
│ str              ┆ str              ┆ str              ┆ i64  ┆ i64   ┆ str              ┆ str   │
╞══════════════════╪══════════════════╪══════════════════╪══════╪═══════╪══════════════════╪═══════╡
│ अथ योगानुशासनम्॥१॥ ┆ Atha             ┆ ɐtʰɐ             ┆ 1    ┆ 1     ┆ And now begins ( ┆ null  │
│                  ┆ yogānuśāsanam    ┆ joːgaːnʊɕaːsɐnɐm ┆      ┆       ┆ atha) the inst…  ┆       │
│ योगश्चित्तवृत्तिनिरो ┆ Yogaścittavṛttin ┆ joːgɐɕtɕɪttɐʋr̩tt ┆ 1    ┆ 2     ┆ Yoga (yogaḥ) is  ┆ null  │
│ धः॥२॥            ┆ irodhaḥ          ┆ ɪnɪroːdʰɐɦ       ┆      ┆       ┆ the suppressio…  ┆       │
│ तदा द्रष्टुः        ┆ Tadā draṣṭuḥ sva ┆ tɐdaː drɐʂʈʊɦ    ┆ 1    ┆ 3     ┆ Then (tadā),     ┆ null  │
│ स्वरूपेऽवस्थानम्॥…    ┆ rūpe'vasthānam   ┆ sʋɐruːpeː'ʋɐstʰa ┆      ┆       ┆ there is an      ┆       │
│                  ┆                  ┆ …                ┆      ┆       ┆ abidi…           ┆       │
│ वृत्तिसारूप्यमितरत्र॥ ┆ Vṛttisārūpyamita ┆ ʋr̩ttɪsaːruːpjɐmɪ ┆ 1    ┆ 4     ┆ On other occasio ┆ null  │
│ ४॥               ┆ ratra            ┆ tɐrɐtrɐ          ┆      ┆       ┆ ns (itaratra),…  ┆       │
│ वृत्तयः पञ्चतय्यः    ┆ Vṛttayaḥ         ┆ ʋr̩ttɐjɐɦ         ┆ 1    ┆ 5     ┆ The (mental) mod ┆ null  │
│ क्लिष्टा अक्…       ┆ pañcatayyaḥ      ┆ pɐɲtɕɐtɐjjɐɦ     ┆      ┆       ┆ ifications (vṛ…  ┆       │
│                  ┆ kliṣṭā ak…       ┆ klɪʂʈaː…         ┆      ┆       ┆                  ┆       │
└──────────────────┴──────────────────┴──────────────────┴──────┴───────┴──────────────────┴───────┘

shape: (5, 7)
┌──────────────────┬──────────────────┬──────────────────┬──────┬───────┬──────────────────┬───────┐
│ Brahmi           ┆ IAST             ┆ IPA              ┆ Book ┆ Sutra ┆ English          ┆ Gloss │
│ ---              ┆ ---              ┆ ---              ┆ ---  ┆ ---   ┆ ---              ┆ ---   │
│ str              ┆ str              ┆ str              ┆ i64  ┆ i64   ┆ str              ┆ str   │
╞══════════════════╪══════════════════╪══════════════════╪══════╪═══════╪══════════════════╪═══════╡
│ तपःस्वाध्यायेश्वरप्र  ┆ Tapaḥsvādhyāyeśv ┆ tɐpɐɦsʋaːdʰjaːje ┆ 2    ┆ 1     ┆ Austerity or     ┆ null  │
│ णिधानानि क…      ┆ arapraṇidhānān…  ┆ ːɕʋɐrɐprɐɳɪdʰa…  ┆      ┆       ┆ Penance (tapas), ┆       │
│                  ┆                  ┆                  ┆      ┆       ┆ …                ┆       │
│ समाधिभावनार्थः    ┆ Samādhibhāvanārt ┆ sɐmaːdʰɪbʰaːʋɐna ┆ 2    ┆ 2     ┆ (Kriyāyoga       ┆ null  │
│ क्लेशतनूकरणार्थ…     ┆ haḥ kleśatanūk…  ┆ ːrtʰɐɦ kleːɕɐt…  ┆      ┆       ┆ should be        ┆       │
│                  ┆                  ┆                  ┆      ┆       ┆ practiced…       ┆       │
│ अविद्यास्मितारागद्वे ┆ Avidyāsmitārāgad ┆ ɐʋɪdjaːsmɪtaːraː ┆ 2    ┆ 3     ┆ Ignorance (in    ┆ null  │
│ षाभिनिवेशा…       ┆ veṣābhiniveśāḥ…  ┆ gɐdʋeːʂaːbʰɪnɪ…  ┆      ┆       ┆ the form of a    ┆       │
│                  ┆                  ┆                  ┆      ┆       ┆ mi…              ┆       │
│ अविद्या           ┆ Avidyā           ┆ ɐʋɪdjaː kʂeːtrɐm ┆ 2    ┆ 4     ┆ Ignorance (in    ┆ null  │
│ क्षेत्रमुत्तरेषां प्रस…  ┆ kṣetramuttareṣāṁ ┆ ʊttɐreːʂãː pr…   ┆      ┆       ┆ the form of a    ┆       │
│                  ┆ prasup…          ┆                  ┆      ┆       ┆ mi…              ┆       │
│ अनित्याशुचिदुःखाना  ┆ Anityāśuciduḥkhā ┆ ɐnɪtjaːɕʊtɕɪdʊɦk ┆ 2    ┆ 5     ┆ Ignorance (avidy ┆ null  │
│ त्मसु नित्यश…       ┆ nātmasu nityaś…  ┆ ʰaːnaːtmɐsʊ nɪ…  ┆      ┆       ┆ ā) is to consi…  ┆       │
└──────────────────┴──────────────────┴──────────────────┴──────┴───────┴──────────────────┴───────┘

shape: (5, 7)
┌──────────────────┬──────────────────┬──────────────────┬──────┬───────┬──────────────────┬───────┐
│ Brahmi           ┆ IAST             ┆ IPA              ┆ Book ┆ Sutra ┆ English          ┆ Gloss │
│ ---              ┆ ---              ┆ ---              ┆ ---  ┆ ---   ┆ ---              ┆ ---   │
│ str              ┆ str              ┆ str              ┆ i64  ┆ i64   ┆ str              ┆ str   │
╞══════════════════╪══════════════════╪══════════════════╪══════╪═══════╪══════════════════╪═══════╡
│ देशबन्धश्चित्तस्य     ┆ Deśabandhaścitta ┆ deːɕɐbɐndʰɐɕtɕɪt ┆ 3    ┆ 1     ┆ Concentration (d ┆ null  │
│ धारणा॥१॥         ┆ sya dhāraṇā      ┆ tɐsjɐ dʰaːrɐɳa…  ┆      ┆       ┆ hāraṇā) is the…  ┆       │
│ तत्र प्रत्ययैकतानता  ┆ Tatra pratyayaik ┆ tɐtrɐ prɐtjɐjɐːi̯ ┆ 3    ┆ 2     ┆ In that --in Dhā ┆ null  │
│ ध्यानम्॥२॥         ┆ atānatā dhyāna…  ┆ kɐtaːnɐtaː dʰ…   ┆      ┆       ┆ raṇā-- (tatra)…  ┆       │
│ तदेवार्थमात्रनिर्भासं ┆ Tadevārthamātran ┆ tɐdeːʋaːrtʰɐmaːt ┆ 3    ┆ 3     ┆ Perfect Concentr ┆ null  │
│ स्वरूपशू…           ┆ irbhāsaṁ svarū…  ┆ rɐnɪrbʰaːsɐ̃ s…   ┆      ┆       ┆ ation (samādhi…  ┆       │
│ त्रयमेकत्र संयमः॥४॥  ┆ Trayamekatra     ┆ trɐjɐmeːkɐtrɐ    ┆ 3    ┆ 4     ┆ The (abovementio ┆ null  │
│                  ┆ saṁyamaḥ         ┆ sɐ̃jɐmɐɦ          ┆      ┆       ┆ ned) triad --i…  ┆       │
│ तज्जयात्प्रज्ञालोकः॥ ┆ Tajjayātprajñālo ┆ tɐdʑdʑɐjaːtprɐdʑ ┆ 3    ┆ 5     ┆ Through the conq ┆ null  │
│ ५॥               ┆ kaḥ              ┆ ɲaːloːkɐɦ        ┆      ┆       ┆ uest (jayāt) o…  ┆       │
└──────────────────┴──────────────────┴──────────────────┴──────┴───────┴──────────────────┴───────┘

shape: (5, 7)
┌────────────────┬────────────────┬────────────────┬──────┬───────┬────────────────┬───────────────┐
│ Brahmi         ┆ IAST           ┆ IPA            ┆ Book ┆ Sutra ┆ English        ┆ Gloss         │
│ ---            ┆ ---            ┆ ---            ┆ ---  ┆ ---   ┆ ---            ┆ ---           │
│ str            ┆ str            ┆ str            ┆ i64  ┆ i64   ┆ str            ┆ str           │
╞════════════════╪════════════════╪════════════════╪══════╪═══════╪════════════════╪═══════════════╡
│ जन्मौषधिमन्त्रतपः ┆ Janmauṣadhiman ┆ dʑɐnmɐːu̯ʂɐdʰɪm ┆ 4    ┆ 1     ┆ The Siddhi-s   ┆ null          │
│ समाधिजाः सिद्…  ┆ tratapaḥsamādh ┆ ɐntrɐtɐpɐɦsɐma ┆      ┆       ┆ or             ┆               │
│                ┆ ij…            ┆ ː…             ┆      ┆       ┆ Supernatural   ┆               │
│                ┆                ┆                ┆      ┆       ┆ P…             ┆               │
│ जात्यन्तरपरिणामः ┆ Jātyantarapari ┆ dʑaːtjɐntɐrɐpɐ ┆ 4    ┆ 2     ┆ The transforma ┆ In other      │
│ प्रकृत्यापूरा…     ┆ ṇāmaḥ          ┆ rɪɳaːmɐɦ       ┆      ┆       ┆ tion (pariṇāma ┆ words, the    │
│                ┆ prakṛtyāpū…    ┆ prɐkr̩t…        ┆      ┆       ┆ ḥ)…            ┆ mould of t…   │
│ निमित्तमप्रयोजकं  ┆ Nimittamaprayo ┆ nɪmɪttɐmɐprɐjo ┆ 4    ┆ 3     ┆ Cause (nimitta ┆ null          │
│ प्रकृतीनां वर…    ┆ jakaṁ          ┆ ːdʑɐkɐ̃         ┆      ┆       ┆ m) (does not   ┆               │
│                ┆ prakṛtīnāṁ…    ┆ prɐkr̩ti…       ┆      ┆       ┆ set…           ┆               │
│ निर्माणचित्तान्य  ┆ Nirmāṇacittāny ┆ nɪrmaːɳɐtɕɪtta ┆ 4    ┆ 4     ┆ The created (n ┆ null          │
│ स्मितामात्रात्…   ┆ asmitāmātrāt   ┆ ːnjɐsmɪtaːmaːt ┆      ┆       ┆ irmāṇa) minds  ┆               │
│                ┆                ┆ ra…            ┆      ┆       ┆ (c…            ┆               │
│ प्रवृत्तिभेदे       ┆ Pravṛttibhede  ┆ prɐʋr̩ttɪbʰeːde ┆ 4    ┆ 5     ┆ (Only) one (ek ┆ null          │
│ प्रयोजकं चित्तमे…  ┆ prayojakaṁ     ┆ ː prɐjoːdʑɐkɐ̃  ┆      ┆       ┆ am) mind (citt ┆               │
│                ┆ citta…         ┆ …              ┆      ┆       ┆ am…            ┆               │
└────────────────┴────────────────┴────────────────┴──────┴───────┴────────────────┴───────────────┘

I don't know why the spreadsheet calls it "Brahmi". Brahmi is an ancient writing system that is definitely not this one. This one is clearly devanagari. IAST is the "International Alphabet of Sanskrit Transliteration." Note that "Sanskrit" refers to the spoken language. Devanagari, IAST, and even Brahmi are different writing systems for the same spoken words and sounds.

In [11]:
def clean(df):
    df = df.rename({
        "Book": "pada",
        "Sutra": "sutra",
        "Brahmi": "devanagari",
        "IAST": "iast",
        "English": "english"
    })
    return df.select(["pada", "sutra", "devanagari", "iast", "english"])

cleaned = [clean(df) for df in data]

all_df = pl.concat(cleaned, how="vertical")
all_df = all_df.with_columns(index=pl.arange(1, all_df.height + 1))

In [13]:
import json

all_df = all_df.select(["index", "pada", "sutra", "devanagari", "iast", "english"])
json_obj = all_df.to_dicts()

with open("yoga_sutras.json", "w") as fp:
    json.dump(json_obj, fp, ensure_ascii=False, indent=2)

#json_obj

Claude recommended the following format. I used something close to it.

```
{
    "id": 1,
    "chapter": 1,
    "verse": 1,
    "sanskrit": "अथ योगानुशासनम्",
    "transliteration": "atha yogānuśāsanam",
    "translation": "Now, the teachings of yoga."
}
```